### PR TITLE
Updates to v0.8.2

### PR DESCRIPTION
**Pull request by cgilmour**
This includes PR #95 with updates to make it work in newer cases.

Test results will be added as comments before merging this to master.

### CODE REVIEW

**Comment by cgilmour** [comment]
### Test 1: Ubuntu / Kubernetes / Romana v0.8.2
Demo script ran to completion, no errors.
```sh-session
$ # let's try to have the frontend load data from the backend
$ kubectl --namespace=tenant-a exec nginx-frontend -- curl 10.1.17.4 --connect-timeout 5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (28) Connection timed out after 5000 milliseconds
error: error executing remote command: Error executing command in container: Error executing in Docker Container: 28
$ # now let's add a policy that permits frontend to connect to the backend
$ romana policy add tenant-a romana-np-frontend-to-backend.json; sleep 5
Policy (romana-np-frontend-to-backend.json) for Tenant (tenant-a) successfully created.
$ # this permits us to connect from frontend to backend
$ kubectl --namespace=tenant-a exec nginx-frontend -- curl 10.1.17.4 --connect-timeout 5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   612  100   612    0     0   1420      0 --:--:-- --:--:-- --:--:--  1423
<!DOCTYPE html>
...
<p><em>Thank you for using nginx.</em></p>
</body>
</html>
$ 
```

**Comment by cgilmour** [comment]
### Test #2: Ubuntu / Devstack / Romana v0.8.2

Install succeeded, but took longer than usual. The pip cache may need updating to make it faster.
IPAM seems to have changed and now doesn't like networking-romana's IPAM request. (HTTP 500 error). Will drop the tags on it and look into a fix.

**Comment by cgilmour** [comment]
### Test 3: Centos / Kubernetes / Romana v0.8.2
Failed with this error on the first attempt. Small change pushed to make the install wait until etcd is up before proceeding to apiserver.
```
TASK [stack/kubernetes/install-master : Start services] ************************
changed: [rt082centos-controller] => (item=etcd)
failed: [rt082centos-controller] => (item=kube-apiserver) => {"failed": true, "item": "kube-apiserver", "msg": "Job for kube-apiserver.service failed because the control process exited with error code. See \"systemctl status kube-apiserver.service\" and \"journalctl -xe\" for details.\n"}
changed: [rt082centos-controller] => (item=kube-controller-manager)
changed: [rt082centos-controller] => (item=kube-scheduler)

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0   
rt082centos-compute01      : ok=31   changed=13   unreachable=0    failed=0   
rt082centos-controller     : ok=53   changed=26   unreachable=0    failed=1   
```

**Comment by cgilmour** [comment]
### Retest 1: Ubuntu / Kubernetes / Romana v0.8.2
Installed successfully. Demo script completed successfully.

**Comment by cgilmour** [comment]
### Retest 2: Ubuntu / Devstack / Romana v0.8.2
Installed slowly but surely. Instances created successfully in Horizon.

**Comment by cgilmour** [comment]
### Retest 3: Centos / Kubernetes / Romana v0.8.2
Install successfully, demo script completed successfully.

We have a winner.

**Comment by jbrendel** [comment]
Nice!

**Pull request merged**
