### PR TITLE
Install openstack (updated)

### PR DESCRIPTION
**Pull request by cgilmour**
(Related to PR #108 but rebased and fixed to work against master.)

New feature for the installer to deploy openstack using packages, and configure/enable Romana.

Tested on AWS by completing the install and running:
```bash
nova boot --flavor m1.micro --image cirros-0.3.4-x86_64-uec --key-name shared-key --nic net-id=$(neutron net-show romana -Fid -f value) --meta romanaSegment=backend b1 --availability-zone=nova:ip-192-168-99-10
nova boot --flavor m1.micro --image cirros-0.3.4-x86_64-uec --key-name shared-key --nic net-id=$(neutron net-show romana -Fid -f value) --meta romanaSegment=backend b1 --availability-zone=nova:ip-192-168-99-11
```

This results in two instances running
```
ubuntu@ip-192-168-99-10:~$ nova list
+--------------------------------------+------+--------+------------+-------------+-----------------+
| ID                                   | Name | Status | Task State | Power State | Networks        |
+--------------------------------------+------+--------+------------+-------------+-----------------+
| 131ea721-ac6e-4f64-9a70-cf29e71249d9 | b1   | ACTIVE | -          | Running     | romana=10.1.2.3 |
| f65721e0-bef3-4cb5-9226-2445eda3860f | b1   | ACTIVE | -          | Running     | romana=10.0.2.3 |
+--------------------------------------+------+--------+------------+-------------+-----------------+
```

SSH and Ping between the instances works.
```sh-session
ubuntu@ip-192-168-99-10:~$ ssh cirros@10.0.2.3
The authenticity of host '10.0.2.3 (10.0.2.3)' can't be established.
RSA key fingerprint is d2:20:67:e0:8a:44:fb:11:be:86:0f:92:26:57:76:ad.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.0.2.3' (RSA) to the list of known hosts.
$ ping 10.1.2.3
PING 10.1.2.3 (10.1.2.3): 56 data bytes
64 bytes from 10.1.2.3: seq=0 ttl=62 time=7.879 ms
64 bytes from 10.1.2.3: seq=1 ttl=62 time=1.686 ms
^C
--- 10.1.2.3 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 1.686/4.782/7.879 ms
$ ssh 10.1.2.3
Host '10.1.2.3' is not in the trusted hosts file.
(fingerprint md5 7c:59:79:a0:d3:e3:74:39:82:09:6b:70:02:58:5c:52)
Do you want to continue connecting? (y/n) y 
cirros@10.1.2.3's password: 
$ 
$ Connection to 10.0.2.3 closed.
```

### CODE REVIEW

**Comment by pritesh** [comment]
Awesome patch looks good!
PS: didn't see horizon, so assuming it will come in later PR.

**Comment by pritesh** [comment]
Update:
ubuntu installation works! great!
centos one fails with:
```
TASK [system : Enable EPEL repository] *****************************************
fatal: [pkdev-os-controller]: FAILED! => {"changed": true, "failed": true, "msg": "You need to be root to perform this command.\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\n"]}
fatal: [pkdev-os-compute01]: FAILED! => {"changed": true, "failed": true, "msg": "You need to be root to perform this command.\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\n"]}
```

**Comment by cgilmour** [comment]
Correct, horizon wasn't working easily so it has been skipped for now.
I'll check into the centos failure. It should be a simple fix.

**Comment by cgilmour** [comment]
Centos install now completes successfully.

**Comment by pritesh** [comment]
ok looks good, works in centos now, thanks.

**Comment by pritesh** [comment]
LGTM

**Pull request merged**
