### PR TITLE
Prevent ansible failure when virbr0 doesn't exist

### PR DESCRIPTION
**Pull request by flashvoid**

### CODE REVIEW

**Comment by cgilmour** [comment]
What was the ansible failure?
Should this be a fix branch off master? (this feature branch is already merged.)

**Comment by flashvoid** [comment]
If interface doesn't exist this script will fail on `virsh --list` causing ansible to fail playbook run.

I guess it's valid for master but right now it needs to be in vagrant branch, we can cherry-pick to master or wait for vagrant branch to be merged.

**Comment by cgilmour** [comment]
The vagrant branch was merged last week.

**Comment by cgilmour** [comment]
I've got a different fix prepared for this problem -- preventing it being created at install time.
I think that's better than extra steps to remove it after installation.

**Comment by jbrendel** [comment]
Should we remove this PR then?

**Comment by cgilmour** [comment]
Deleting this PR and the feature/vagrant branch.

**Pull request closed without merging**
