### PR TITLE
More installer changes

### PR DESCRIPTION
**Pull request by cgilmour**
A handful of changes to support installing Romana with different CIDRs.

1) Adds a `docker_cidr` variable to specify the IP and subnet that `docker0` interface will bind to.
2) Makes sure the docker configs are in place before it's installed, because it gets started automatically. (Applying config after means it needs a restart)
3) Make sure we calculate the host bits based on the `romana_cidr` (16 - subnet prefix length) and put that in the config.
4) Sort the hosts (for AWS) so the inventory is consistent on multiple runs of the installer. They're discovered dynamically, so the values would be in an arbitrary order. Sorting by private IP seemed reasonable.

### CODE REVIEW

**Comment by cgilmour** [comment]
A command-line that uses allthethings is like this:
`./romana-setup -n newcidrs -s kubernetes install -e romana_cidr=172.16.0.0/12 -e host_cidr=10.0.0.0/24 -e docker_cidr=192.168.255.1/24`

Special note for AWS: The CIDR prefix needs to be at least 16. It really doesn't like having a 10/8.

**Comment by jbrendel** [comment]
Is the docker_cidr even used? If I recall correctly, our docker0 interface doesn't even carry an address? Could be wrong, I don't currently have a cluster to look at.

**Comment by cgilmour** [comment]
It's not used in a useful way, but it is there [by default](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/) after installation. Most of the time, nobody cares because 172.16/12 is an uncommon CIDR to use.
But when we want to use it, this variable helps us put docker in a different spot.

**Comment by jbrendel** [comment]
As long as this is documented in that way somewhere...

**Comment by cgilmour** [comment]
Added documentation (in PR #100) so that we can get this closed.

**Pull request merged**
